# Generated by Django 4.2.27 on 2026-07-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
