# Generated by Django 6.0.7 on 2026-07-19 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Octane', 'Octane'), ('Diesel', 'Diesel')], max_length=20)),
                ('tank_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_odometer', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
                'ordering': ['-created_at'],
            },
        ),
    ]
